version: 2.1
orbs:
  wlecome: circleci/welcom-orb@0.4.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Hello 
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world 
  print_vals:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "print values"
          command: |
            echo << pipeline.id>> 
            echo END!
      - run:
          name: "print env var"
          command: |
            echo ${NAME}
workflows:
  welcome:
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_vals:
          requires:
            - print_hello
            - print_world 