version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
defaults: &defults
  docker:
      - image: circleci/node:13.8.0
jobs:
  print_hello:
    <<: *defults
    steps:
      - run: echo Hello 
  print_world:
    <<: *defults
    steps:
      - run: echo world 
  print_vals:
    <<: *defults
    steps:
      - run:
          name: "print values"
          command: |
            echo << pipeline.id>> 
            echo END!
      - run:
          name: "print env var"
          command: |
            echo ${NAME}
  save_hello_world_output:
    <<: *defults
    steps:
      - run: echo "hello world !" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output:
    <<: *defults
    steps:
      - attach_workspace:
          at: ~/ 
      - run: cat ~/output.txt
workflows:
  welcome:
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_vals:
          requires:
            - print_hello
            - print_world 
      - save_hello_world_output 
      - print_output:
          requires:
            - save_hello_world_output